language: node_js
notifications:
  email: false
node_js:
  - node
  - lts/*
  - 8
after_success:
  - npx codecov
  - npm i @semantic-release/changelog
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
